# Generated by Django 2.1.7 on 2019-03-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationlog',
            name='event',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='happy_hour',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
