# Generated by Django 2.2.27 on 2023-06-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='auto_subscribe',
            field=models.BooleanField(default=True, help_text='Enabling this will subscribe you to all newly created topics and you will receive email updates for subscribed topics.'),
        ),
    ]
